name: Schedule
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: yohix/todoist-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: cf925b4b9b52fb450e36addf79258897
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
